#!/bin/sh

## 
# Gracenote API script to get theaters by name and location.
#
# Syntax:
#
#     gracenote-get-theaters-by-name-and-location <name> [latitude longitude] [radius] [units]
#
# Example:
#
#     $ gracenote-get-theaters-by-name-and-location "AMC Empire 25" 40.7527 -73.9772
#
# Defaults:
#
#    * `latitude`: $LATITUDE
#    * `longitude`: $LONGITUDE
#    * `radius`: 1
#    * `units`: `km` a.k.a. kilometers.
#
# ## Tracking
#
#   * Command: gracenote-get-theaters-by-name-and-location-to-ids
#   * Version: 3.2.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-07
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

set -euf
source gracenote-helpers

## Args
name="${1:-}"
latitude="${2:-$LATITUDE}"
longitude="${3:-$LONGITUDE}"
radius="${4:-1}"
units="${5:-km}"

## Preflight
[ -z "$name" ] && die_var name
[ -z "$latitude" ] && die_var latitude
[ -z "$longitude" ] && die_var longitude
[ -z "$radius" ] && die_var radius
[ -z "$units" ] && die_var units

## Main
"$CURL" -sSLG "http://data.tmsapi.com/v1.1/theatres" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "lat=$latitude" \
  --data-urlencode "lng=$longitude" \
  --data-urlencode "radius=$radius" \
  --data-urlencode "units=$units" |
"$JQ" .
