#!/bin/sh

## 
# Gracenote API script to get theatres by zip.
#
# Syntax:
#
#     gracenote-get-theatres-by-zip [zip] [[radius] units]
#
# Example:
#
#     $ gracenote-get-theatres-by-zip 10017
#
# Defaults:
#
#    * `zip`: $ZIP
#    * `radius` is `1`.
#    * `units` is `km` a.k.a. kilometers.
#
#
# ## Tracking
#
#   * Command: gracenote-get-theatres-by-zip
#   * Version: 3.3.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-14
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

set -euf
. gracenote-helpers

## Args
zip="${1:-${ZIP:-}}"
radius="${2:-1}"
units="${3:-km}"

## Preflight
[ -z "$zip" ] && die_var zip
[ -z "$radius" ] && die_var radius
[ -z "$units" ] && die_var units

## Main
"$CURL" -vSLG "http://data.tmsapi.com/v1.1/theatres" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "zip=$zip" \
  --data-urlencode "radius=$radius" \
  --data-urlencode "units=$units" |
"$JQ" .
