#!/bin/sh

## 
# Gracenote API script to get theatre showings
#
# Syntax:
#
#     $ gracenote-get-theatre-showings <theatre id> [[start date] number of days]
#
# Example:
#
#     $ export GRACENOTE_API_KEY=123456679
#     $ gracenote-get-theatre-showings 7503
#
# Defaults:
#
#   * `start date` is today.
#   * `number of days` is 1.
#
#
# ## Filtering
#
# Example that outputs each movie id and an array of the movie's showtime datetimes:
#     
#     $ gracenote-get-theatre-showings 7503  | jq 'map({tmsId, dateTimes: .showtimes | map(.dateTime)})'
#     [
#       {
#		  "tmsId": "MV008029970000",
#		  "dateTimes": [
#		    "2017-09-01T10:00",
#		    "2017-09-01T16:05",
#		    "2017-09-01T19:20"
#		  ]
#		},
#		{
#		  "tmsId": "MV000088200000",
#		  "dateTimes": [
#		    "2017-09-01T10:00",
#		  ]
#		},
#		{
#		  "tmsId": "MV009698390000",
#		  "dateTimes": [
#		      "2017-09-01T10:00",
#		      "2017-09-01T13:20",
#		  ]
#		}
#	  ]
#
#
# ## Tracking
#
#   * Command: gracenote-get-theaters-by-location
#   * Version: 2.0.0
#   * Created: 2017-08-22
#   * Updated: 2017-08-24
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

theatreId="$1"
startDate="${2:-$(date -u '+%Y-%m-%d')}"
numDays="${3:-1}"

curl -sSLG "http://data.tmsapi.com/v1.1/theatres/$theatreId/showings" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "startDate=$startDate" \
  --data-urlencode "numDays=$numDays"
