#!/bin/sh

## 
# Gracenote API script to get movies by title.
#
# Syntax:
#
#     gracenote-get-movies-by-title <title>
#
# Example:
#
#     $ export GRACENOTE_API_KEY=123456679
#     $ gracenote-get-movies-by-title "Atomic Blonde"
#
#
# ## Tracking
#
#   * Command: gracenote-get-movies-by-title
#   * Version: 3.1.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-07
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

## Start
set -euf
out() { printf %s\\n "$*" ; }
err() { >&2 printf %s\\n "$*" ; }
die() { >&2 printf %s\\n "$*" ; exit 1 ; }
cmd() { command -v $1 >/dev/null 2>&1 ; }
die_cmd() { die "Command needed: $1" ; }
die_var() { die "Variable needed: $1" ; }

## Args
title="${1:-}"

## Cmds
CURL=${CURL:-curl}; cmd "$CURL" || die_cmd "$CURL"
JQ=${JQ:-jq}; cmd "$JQ" || die_cmd "$JQ"

## Preflight
[ -z ${GRACENOTE_API_KEY+x} ] && die_var GRACENOTE_API_KEY
[ -z "$title" ] && die_var title

## Main
"$CURL" -sSLG "http://data.tmsapi.com/v1.1/programs/search" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "entityType=movie" \
  --data-urlencode "q=$title" \
  --data-urlencode "queryFields=title" |
"$JQ" .
