#!/bin/sh

## 
# Gracenote API script to get theatres by location, and output the theatres' ids.
#
# Syntax:
#
#     gracenote-get-theatres-by-location-to-ids [latitude longitude] [[radius] units]
#
# Example:
#
#     $ gracenote-get-theatres-by-location-to-ids 40.7527 -73.9772
#
# Defaults:
#
#    * `latitude`: $LATITUDE
#    * `longitude`: $LONGITUDE
#    * `radius` is `1`.
#    * `units` is `km` a.k.a. kilometers.
#
#
# ## Tracking
#
#   * Command: gracenote-get-theatres-by-location-to-ids
#   * Version: 3.2.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-07
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

set -euf
. gracenote-helpers
	    
## Args
latitude="${1:-${LATITUDE:-}}"
longitude="${2:-${LONGITUDE:-}}"
radius="${3:-1}"
units="${4:-km}"

## Preflight
[ -z "$latitude" ] && die_var latitude
[ -z "$longitude" ] && die_var longitude
[ -z "$radius" ] && die_var radius
[ -z "$units" ] && die_var units

## Main
"$CURL" -sSLG "http://data.tmsapi.com/v1.1/theatres" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "lat=$latitude" \
  --data-urlencode "lng=$longitude" \
  --data-urlencode "radius=$radius" \
  --data-urlencode "units=$units" |
"$JQ" -r ".[] 
  | .theatreId"
