#!/bin/sh

## 
# Gracenote API script to get one celebrity.
#
# Syntax:
#
#     gracenote-get-celebrity <id>
#
# Example:
#
#     $ gracenote-get-celebrity 1234
#
#
# ## Tracking
#
#   * Command: gracenote-get-celebrity
#   * Version: 3.3.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-14
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

set -euf
. gracenote-helpers

## Args
id="${1:-}"

## Preflight
[ -z "$id" ] && die_var title

## Main
"$CURL" -sSLG "http://data.tmsapi.com/v1.1/celebs/$id" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY"
"$JQ" .
