#!/bin/sh

## 
# Gracenote API script to get theatres by location
#
# Syntax:
#
#     gracenote-get-theatres-by-location [latitude longitude] [[radius] units]
#
# Example:
#
#     $ export GRACENOTE_API_KEY=123456679
#     $ gracenote-get-theatres-by-location 40.7527 -73.9772
#
# Defaults:
#
#    * `latitude`: $LATITUDE
#    * `longitude`: $LONGITUDE
#    * `radius` is `1`.
#    * `units` is `km` a.k.a. kilometers.
#
#
# ## Tracking
#
#   * Command: gracenote-get-theaters-by-location
#   * Version: 3.1.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-07
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

## Start
set -euf
out() { printf %s\\n "$*" ; }
err() { >&2 printf %s\\n "$*" ; }
die() { >&2 printf %s\\n "$*" ; exit 1 ; }

## Args
latitude="${1:-$LATITUDE}"
longitude="${2:-$LONGITUDE}"
radius="${3:-1}"
units="${4:-km}"

## Preflight
[ -z ${GRACENOTE_API_KEY+x} ] && die "GRACENOTE_API_KEY missing"

## Main
curl -sSLG "http://data.tmsapi.com/v1.1/theatres" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "lat=$latitude" \
  --data-urlencode "lng=$longitude" \
  --data-urlencode "radius=$radius" \
  --data-urlencode "units=$units"
