#!/bin/sh

## 
# Gracenote API script to get showings by theatre id and movie id
#
# Syntax:
#
#     gracenote-get-showings-by-theatre-id-and-movie-id <theatre id> <movie id> [[start date] number of days]
#
# Example:
#
#     $ export GRACENOTE_API_KEY=123456679
#     $ gracenote-get-showings-by-theatre-id-and-movie-id 7503 1234
#
# Defaults:
#
#   * `start date`: today
#   * `number of days`: 1
#
#
# ## Tracking
#
#   * Command: gracenote-get-showings-by-theatre-id-and-movie-id
#   * Version: 3.0.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

theatreId="$1"
movieId="$2"
startDate="${3:-$(date '+%Y-%m-%d')}"
numDays="${4:-1}"

curl -sSLG "http://data.tmsapi.com/v1.1/theatres/$theatreId/showings" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "startDate=$startDate" \
  --data-urlencode "numDays=$numDays" |
jq  ".[] 
  | select(.tmsId==\"$movieId\") .showtimes 
  | map(del(.theatre))"
