#!/bin/sh

## 
# Gracenote API script to get showings by theatre id and movie id,
# and output raw timestamps
#
# Syntax:
#
#     gracenote-get-showings-by-theatre-id-and-movie-id-to-timestamps <theatre id> <movie id> [[start date] number of days]
#
# Example:
#
#     $ export GRACENOTE_API_KEY=123456679
#     $ gracenote-get-showings-by-theatre-id-and-movie-id-to-timestamps 7503 1234
#
# Defaults:
#
#   * `start date`: today
#   * `number of days`: 1
#
#
# ## Tracking
#
#   * Command: gracenote-get-showings-by-theatre-id-and-movie-id-to-timestamps
#   * Version: 3.2.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-07
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

## Start
set -euf
out() { printf %s\\n "$*" ; }
err() { >&2 printf %s\\n "$*" ; }
die() { >&2 printf %s\\n "$*" ; exit 1 ; }
cmd() { command -v $1 >/dev/null 2>&1 ; }
die_cmd() { die "Command needed: $1" ; }
die_var() { die "Variable needed: $1" ; }

## Args
theatreId="${1:-}"
movieId="${2:-}"
startDate="${2:-$(date '+%Y-%m-%d')}"
numDays="${3:-1}"

## Cmds
CURL=${CURL:-curl}; cmd "$CURL" || die_cmd "$CURL"
JQ=${JQ:-jq}; cmd "$JQ" || die_cmd "$JQ"

## Preflight
[ -z ${GRACENOTE_API_KEY+x} ] && die_var GRACENOTE_API_KEY
[ -z "$theatreId" ] && die_var theatreId
[ -z "$movieId" ] && die_var movieId
[ -z "$startDate" ] && die_var startDate
[ -z "$numDays" ] && die_var numDays

## Main
"$CURL" -sSLG "http://data.tmsapi.com/v1.1/theatres/$theatreId/showings" \
  --data-urlencode "api_key=$GRACENOTE_API_KEY" \
  --data-urlencode "startDate=$startDate" \
  --data-urlencode "numDays=$numDays" |
"$JQ" -r ".[] 
  | select(.tmsId==\"$movieId\") .showtimes 
  | map(.dateTime) 
  | .[]"
